- package-lock.json
- package.json
- src/App.tsx
- src/components/EditorBax.tsx
- src/components/Navbar.tsx
- src/components/ToggleTheme.tsx
- src/core/apis/Board.api.ts
- src/core/apis/Image.api.ts
- src/core/apis/Member.api.ts
- src/core/atoms/Theme.atom.ts
- src/core/enum/ThemeEnum.ts
- src/layouts/DefaultLayout.tsx
- src/pages/boards/BoardInsertForm.tsx
- src/pages/home/components/MainCharacters.tsx
- src/pages/member/ApiKeyUpdateForm.tsx
- src/pages/todo/components/TodoDayContent.tsx
- src/pages/todo/components/TodoWeekRaid.tsx
- src/styles/Color.css
- src/styles/Reset.css
- src/styles/components/PageNation.css
- src/styles/layouts/DefaultLayout.css
- src/styles/pages/Auth.css
- src/styles/pages/CommentsIndex.css
- src/styles/pages/HomeIndex.css
- src/styles/pages/TodoIndex.css
- 공지사항 작성 추가
- 다크모드 반영
- api key 업데이트 추가
- 메인 캐릭터 변경 롤백
> 공지사항 + 다크모드

- src/App.tsx
- src/components/SignUpCharactersNotify.tsx
- src/core/apis/Auth.api.ts
- src/core/func/todo.fun.ts
- src/layouts/DefaultLayout.tsx
- src/pages/auth/SignUp.tsx
- src/pages/auth/SignUpCharacters.tsx
- src/pages/auth/components/EmailTimer.tsx
- src/pages/home/HomeIndex.tsx
- src/pages/todo/TodoIndex.tsx
- src/styles/components/Navbar.css
- src/styles/layouts/DefaultLayout.css
- src/styles/pages/Auth.css
> Auth 기능 추가

- public/ads.txt
- src/core/apis/Comment.api.ts
- src/pages/comments/CommentsIndex.tsx
- src/pages/comments/components/Comment.tsx
> 방명록 수정 삭제 기능 추가

- src/components/Modal.tsx
- src/components/SortedScheduleList.tsx
- src/components/form/Checkbox.tsx
- src/components/form/FriendCharacterSelector/SelectorItem.tsx
- src/components/form/FriendCharacterSelector/index.tsx
- src/core/apis/schedule.api.ts
- src/core/hooks/queries/schedule/useSchedule.ts
- src/core/types/schedule.d.ts
- src/core/utils/queryKeyGenerator.ts
- src/pages/schedule/ScheduleIndex.tsx
- src/pages/schedule/components/FormModal.tsx
* 일정 초대받은 깐부 API 및 UI 수정
* 일정 모달에서 읽기 전용 UI 수정
* @components/Modal: 닫힐 때 transition 제거
> 일정 모달 - 읽기 전용 중간 배포

- src/App.tsx
- src/core/apis/cube.api.ts
- src/core/types/cube.d.ts
- src/pages/cube/CharacterSelectionModal.tsx
- src/pages/cube/CubeCard.tsx
- src/pages/cube/CubeIndex.tsx
- src/pages/cube/CubeStatistics.tsx
베타버전 만들어봤어요
Cursor AI로 만든거라 코드 난잡할 수 있는데 한번 봐주시면 감사하겠습니다
> LOAT-30 큐브 컨텐츠 API 베타

- src/core/hooks/queries/community.ts
- src/core/types/community.d.ts
- src/pages/main/CommunityList.tsx
- src/pages/main/components/PostItem.tsx
- src/pages/main/components/UploadPost.tsx
- 캐릭터 이미지 출력
- 카테고리 별 출력
- 좋아요 누르면 바로 반응
> 커뮤니티 1차 수정

- src/pages/main/CommunityDetail.tsx
- src/pages/main/CommunityList.tsx
- src/pages/main/components/PostItem.tsx
- 좋아요 갱신 안되는 오류 수정
- 다크모드일 때 카테고리 글씨 안보이는 오류 수정
- 댓글 닉네임 공개/비공개 글씨 출력
- 내가 쓴 게시글 삭제 기능 추가
> 커뮤니티 2차 업데이트

- src/core/types/notification.d.ts
- src/layouts/common/Header/NotificationButton.tsx
- src/pages/comment/CommentsIndex.tsx
- src/pages/main/CommunityDetail.tsx
- 답글 알림 연결
- 에러(삭제된 게시글) 클릭 시 뒤로가기
- 기존 방명록 작성 폼 미출력
> 커뮤니티 답글 알림 연결

- src/pages/main/CommunityList.tsx
- src/pages/main/components/EditForm.tsx
- src/pages/main/components/PostItem.tsx
- src/pages/main/components/UploadPost.tsx
- 게시글 수정
- 여러 이미지 출력 수정(드래그)
- 게시글 작성 중 이미지 삭제 기능 추가
- 이미지 사진 크기, 위치 조정
> 커뮤니티 기능 연결

- src/components/todo/TodoList/CharacterInformation.tsx
- src/core/apis/character.api.ts
- src/core/hooks/mutations/character/useRecoveryCharacter.ts
- src/core/hooks/queries/character/useDeletedCharacters.ts
- src/core/utils/queryKeyGenerator.ts
- src/pages/todo/CharacterSetting.tsx
- src/pages/todo/components/DeletedCharacterRecovery.tsx
> ADD: 캐릭터 삭제 복구 기능

- src/App.tsx
- src/components/todo/TodoList/DailyContents.tsx
- src/components/todo/TodoList/WeeklyContents.tsx
- src/components/todo/TodoList/WeeklyRaids/RaidItem.tsx
- src/components/todo/TodoList/element/Check.tsx
- src/core/atoms/auth.atom.ts
- src/core/hooks/useAuthActions.ts
- src/layouts/DefaultLayout.tsx
- All daily todos being checked when adding a custom daily todo
- Updated daily todo all-check-design
- Test removing Google ads by member
> Fixed functionality around daily todos visibility + Tested removing Google ads per member

- src/components/todo/TodoList/DailyContents.tsx
- src/components/todo/TodoList/WeeklyContents.tsx
- src/components/todo/TodoList/element/Check.tsx
- src/core/constants/theme.ts
- Changed the opacity of completed Todo items from 0.3 to 0.5 in DailyContents and WeeklyContents components for better visibility.
- Updated the color for the done state in the Check component to use the new gray1 theme color for improved consistency across the application.
- Added gray1 color definition to the light and dark themes for enhanced theming support.
> style: Update opacity and color styles in Todo components

- src/components/Calc.tsx
- src/components/Dial.tsx
- Integrated a new auction calculator feature in the Dial component.
- Imported necessary icons and modal components for the auction calculator.
- Added functionality to open the auction calculator modal with a button click.
- Styled the modal content for better user experience.
> feat: Add auction calculator modal to Dial component

- src/core/types/lostark.d.ts
- src/core/utils/index.ts
- Added "환수사" to the ClassName type in lostark.d.ts for expanded character support.
- Updated the getIsSpecialist function to include "환수사" as a specialist class, enhancing the classification logic.
> feat: Update class types and specialist check for Lost Ark

- src/App.tsx
- src/core/apis/admin.ads.api.ts
- src/core/types/admin.ads.d.ts
- src/pages/admin/AdminIndex.tsx
- Introduced a new route for the admin section in the App component.
- Integrated the AdminIndex component within the new route, ensuring it is protected by the PageGuard for access control.
- Enhanced the routing structure to accommodate future admin features.
> feat: Add admin route and integrate AdminIndex component

- src/components/todo/TodoList/WeeklyRaids/EditModal.tsx
- src/components/todo/TodoList/WeeklyRaids/RaidItem.tsx
- src/components/todo/TodoList/element/GatewayGauge.tsx
- src/core/apis/todo.api.ts
- src/core/constants/index.ts
- src/core/hooks/mutations/todo.ts
- src/core/types/character.d.ts
- src/core/types/todo.d.ts
- 레이드를 완료하면 더보기 버튼생성
- 더보기 버튼 클릭시 해당하는 만큼 골드 차감
- 주간 레이드 편집에서 버스 골드 계산
- 주간 레이드 초기화시 더보기는 초기화, 버스는 초기화X
> 주간 레이드 더보기, 버스 골드 차감 기능 개발

- src/components/todo/Profit.tsx
- src/components/todo/TodoList/WeeklyRaids/RaidItem.tsx
- src/core/types/character.d.ts
- Modified Profit component to accumulate realGold instead of gold from todos.
- Updated RaidItem component to display realGold when character is a goldCharacter.
- Enhanced TodoRaid type definition to include realGold for improved data integrity.
> feat: Update todo gold handling to use realGold property

- src/components/todo/TodoList/element/GatewayGauge.tsx
- src/core/types/character.d.ts
- src/pages/todo/CharacterSetting.tsx
- Always show "더보기" button
- Add toggle for "더보기" button visibility in character settings
> "더보기" 기능 관련 업데이트

- src/pages/logs/LogsIndex.tsx
> 로그 임시 디자인 화면

- src/components/todo/TodoList/DailyContents.tsx
- src/core/apis/mainAxios.ts
- src/core/apis/todo.api.ts
- src/core/hooks/mutations/todo.ts
- Delete checkDailyTodoAll API and mutation hooks
- Remove unused import in DailyContents component
- Update error handling in mainAxios for rate limit errors
> refactor: Remove unused daily todo all check functionality

- src/components/todo/TodoList/DailyContents.tsx
- src/core/apis/mainAxios.ts
- src/core/apis/todo.api.ts
- src/core/hooks/mutations/todo.ts
- Implement new API endpoint for checking all daily todos
- Create mutation hook for daily todo all check
- Update DailyContents component to use new all check mutation
> feat: Add daily todo all check functionality

- src/layouts/common/Header/index.tsx
- Uncomment the timeline menu item in the Header component
- Restore "/logs" route with "타임라인" (Timeline) title
> feat: Re-enable timeline menu item in Header

- src/components/Dial.tsx
- src/components/todo/TodoList/CharacterInformation.tsx
- src/core/apis/character.api.ts
- src/core/constants/index.ts
- src/core/hooks/mutations/character/useAddCharacter.ts
- src/core/hooks/mutations/character/useUpdateCharacter.ts
- src/core/hooks/mutations/character/useUpdateCharacterName.ts
- src/core/types/character.d.ts
- src/pages/todo/components/DeletedCharacterRecovery.tsx
"전체"에서 "단일"로 바꾸면서 분리
- 캐릭터 레벨 업데이트
- 캐릭터 이름 변경
- 캐릭터 추가
> feat: 캐릭터 업데이트 수정

- src/App.tsx
- src/components/form/DatePicker.tsx
- src/core/apis/schedule.api.ts
- src/core/constants/index.ts
- src/core/hooks/queries/schedule.ts
- src/core/types/schedule.d.ts
- src/core/utils/queryKeyGenerator.ts
- src/layouts/common/Header/index.tsx
- src/pages/schedule/ScheduleIndex.tsx
- src/pages/schedule/ScheduleIndex2.tsx
- src/pages/schedule/components/FormModal.tsx
> feat: 일정 화면 개편

- src/components/SortedScheduleList.tsx
- src/core/atoms/todo.atom.ts
- src/core/constants/index.ts
- src/layouts/common/Header/index.tsx
- src/pages/schedule/ScheduleIndex2.tsx
- src/pages/schedule/components/FormModal.tsx
- 일반 달력으로 고정된 후 다른 화면으로 이동하고 다시 달력 키면 로아 달력으로 바껴있는 오류 수정
- 화면을 넘어가면 스크롤해서 보이도록 수정
- 토/일 색깔 수정
- 우측 상단 이메일->아이콘으로 변경
> fix: 일정 화면 수정

- src/pages/schedule/ScheduleIndex2.tsx
- Update color assignments for weekdays in WeekdayHeader and DateItem components
- Ensure correct color representation for Saturday and Sunday based on the showWen prop
- Improve readability and maintainability of color assignment logic
> style: Refine weekday color logic in ScheduleIndex2 component

- src/core/constants/index.ts
- Change BASE_URL from localhost to the production API URL for deployment readiness
- Comment out the localhost URL for clarity and future reference
> fix: Update BASE_URL to point to production API endpoint

- src/core/apis/content.api.ts
- src/core/apis/friend.api.ts
- src/core/apis/schedule.api.ts
- Change API paths from v4 to v1 for consistency across services
- Ensure all relevant functions in content.api.ts, friend.api.ts, and schedule.api.ts are updated to reflect the new endpoint structure
> fix: Update API endpoints for content, friend, and schedule services

- src/core/apis/todo.api.ts
- Simplify the structure of the getCustomTodos function by consolidating the API call logic
- Ensure consistent parameter handling for friendUsername in the API request
> fix: Refactor getCustomTodos API call for improved readability

- src/components/todo/TodoList/CharacterInformation.tsx
- src/components/todo/TodoList/WeeklyRaids/CharacterRaidProfit.tsx
- src/components/todo/TodoList/WeeklyRaids/EditModal.tsx
- src/components/todo/TodoList/WeeklyRaids/RaidItem.tsx
- src/core/constants/index.ts
- src/core/types/character.d.ts
- 캐릭터 귀속 골드 추가
- 더보기시 컨텐츠에 캐릭터 귀속 골드가 있다면 귀속 골드가 빠짐
- 캐릭터 전투력 추가 및 캐릭터 등록 안되는 오류 수정
> feat: 캐릭터 귀속 골드 + 전투력

- src/App.tsx
- src/core/types/logs.d.ts
- src/layouts/common/Header/index.tsx
- src/pages/logs/LogsIndex.tsx
- src/pages/main/HomeIndex.tsx
> feat: 타임라인 화면 복구

- src/assets/svg/CheckAllIcon.tsx
- src/components/todo/Profit.tsx
- src/core/constants/index.ts
- src/pages/logs/LogsIndex.tsx
> feat: 오일완 기능 복원

- src/pages/main/HomeIndex.tsx
- src/pages/main/components/LogsProfitGraph.tsx
- 기존 주간 수익 요약 삭제
- 주간 내 수익 현황 날짜 출력 잘못나오는거 수정
- 주간 레이드 일정 임시 미출력(버그 수정해야함)
> fix: 메인 화면 자잘하게 수정

- src/components/todo/Profit.tsx
- src/components/todo/TodoList/CharacterInformation.tsx
- src/components/todo/TodoList/WeeklyRaids/CharacterRaidProfit.tsx
- src/components/todo/UncheckedSummaryModal.tsx
- src/pages/friend/FriendTodo.tsx
- src/pages/todo/TodoIndex.tsx
- 일일 수익, 주간 수익 컴팩트화
- "골드 획득 캐릭터" 아이콘화
- 캐릭터 귀속 골드 축소
- 요약 기능 추가
> feat: 숙제 탭 UI/UX 수정

- src/components/todo/TodoList/Elysian.tsx
- src/components/todo/TodoList/index.tsx
- src/core/apis/todo.api.ts
- src/core/hooks/mutations/todo.ts
- src/core/hooks/useSeasonalEffect.ts
- src/core/types/todo.d.ts
- src/layouts/DefaultLayout.tsx
- src/layouts/FallingLeaves.tsx
- src/layouts/WideDefaultLayout.tsx
- 주간 숙제 '낙원' 원클릭 전체 완료 기능 추가
- 계절에 따른 동적 배경 효과 기능 추가
> feat: 낙원 버그 수정 및 계절효과 변경
